### ISSUE TITLE
UnicodeDecodeError: 'utf-8'

### ISSUE THREAD

**Issue by LIMonRUS** [FromDarkHell/BL3ShiftRedeemer#1]
have an error in exe file
![image](https://user-images.githubusercontent.com/22144698/77821169-1df53c00-70f9-11ea-9787-d5d00dfb818e.png)

**Comment by FromDarkHell** [comment]
Try out this file, its due to the fact that your system language is in Russian, it still might not work since my ways of detection are kinda specific but: [Borderlands 3 Auto Redeemer.zip](https://github.com/FromDarkHell/BL3ShiftRedeemer/files/4397465/Borderlands.3.Auto.Redeemer.zip)

**Comment by LIMonRUS** [comment]
![image](https://user-images.githubusercontent.com/22144698/77844273-0e83fa80-71ae-11ea-9c20-9fce5ab73dba.png)
